### ISSUE TITLE
PACKAGE.yaml requirements add tcp/ip

### ISSUE THREAD

**Issue by immetoo** [fr3nd/msxhub-packages#63]
All tcp/ip packages should have a requirement on;
"UNAPI_TCP/IP" or "UNAPI-NETWORK"

This because it is a hardware requirement.

**Comment by immetoo** [comment]
I would vote for 'UNAPI-NIC' and an hardware label

**Comment by fr3nd** [comment]
I have added both `TCP/IP-UNAPI` and `ETH-UNAPI`requirements. I have finally chosen these names because they are the official ones (see https://github.com/Konamiman/MSX-UNAPI-specification)

* https://msxhub.com/list_requirements

I have added `ETH-UNAPI` although I'm not sure if it will be used in any package.

Thanks for the suggestion
