### ISSUE TITLE
Missing audio requirements

### ISSUE THREAD

**Issue by immetoo** [fr3nd/msxhub-packages#82]
There are few missing audio requirements;
- SCC+
- PSG2
- SN_049H

see:
https://www.msx.org/wiki/MSX_Cartridge_Shop_MegaFlashROM_SCC%2B_SD
and manual of realfun3;
https://www.xl2s.tk/

**Comment by fr3nd** [comment]
Hi @immetoo 

I'm aware of SCC+, and I guess that with PSG2 you mean double PSG, right? I think both are not very used among software. That's why they are not included.

I'm also not familiar with SN_049H. Apart from Realfun 3, is there any other software using it? How can it be installed in a real MSX? I see that Realfun 3 is designed to run directly in an emulator, although in theory it should work in a real MSX with a lot of upgrades.

I'm not sure if it's worth adding them, however, if you can provide with the SVG files with the same style as the other requirements (see https://msxhub.com/list_requirements) I'll gladly add them.

**Comment by immetoo** [comment]
Yes PSG2 or PSG_10H like listed on; https://map.grauw.nl/resources/msx_io_ports.php
Currently i don't need them to be added, just was looking at realfun3 as another possible msxhub package.

The reason why i looked at this music tracker, because it is not possible to make human emotions in msx music.
So it is safe for kids !! (mid and mod files are already dangerous)

An FM msx tracker is not granular enough to produce emotions.
With PCM don't use 11bit of higher or filter to 8bit ADPCM to make it safe.
